import './sass/main.scss';
import './js/components/fetchMovieByInput.js';
import './js/components/fetchMovieByTrending.js';
import './js/components/fetchMovieForModal';
import './js/components/pagination';
import './js/components/header.js';
import './js/components/team.js';
import './js/components/setToStorage';
import './js/services/darcmodMine';